// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCr-_GitT6gfyWFzW6WUnZXt6HIQv9mtsY',
    appId: '1:151083432541:android:5df7d52208c82dc08a2bb4',
    messagingSenderId: '151083432541',
    projectId: 'udemy-shop-app-e94ee',
    databaseURL: 'https://udemy-shop-app-e94ee-default-rtdb.firebaseio.com',
    storageBucket: 'udemy-shop-app-e94ee.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3eXDaUnJQ_oHGEzoj99dtCnBk3Vuo18U',
    appId: '1:151083432541:ios:be76bfbc705be43f8a2bb4',
    messagingSenderId: '151083432541',
    projectId: 'udemy-shop-app-e94ee',
    databaseURL: 'https://udemy-shop-app-e94ee-default-rtdb.firebaseio.com',
    storageBucket: 'udemy-shop-app-e94ee.firebasestorage.app',
    iosBundleId: 'com.example.pennysmart',
  );
}
